branches:
  only:
    - master

dist: trusty

sudo: false

addons:
  apt:
    packages:
      - xvfb

language: node_js
node_js:
  - "8.9.4"

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - .eslintcache
    - $HOME/.cache/electron-builder

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --force

script:
  - yarn lint
  - yarn build:prod
  - yarn test

notifications:
  email:
    on_success: never
    on_failure: change